spring:
  datasource:
    username: postgres
    password: chuu
    url: jdbc:postgresql://localhost:5432/postgres
  write-datasource:
    username: postgres
    password: chuu
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    properties:
      hibernate:
        format_sql: true